apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: australia-southeast2-docker.pkg.dev/teja-sit737-prac10/docker-repo/node-app:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred  # This references the secret we created