apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: LoadBalancer
  selector:
    app: node-app  # Must match deployment's labels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000  # Optional: specify node port